### ISSUE TITLE
missing -y on yum commands

### ISSUE THREAD

**Issue by bangroot** [aws-quickstart/quickstart-linux-utilities#16]
`quickstart-cfn-tools.source` lines 277, 278, 285,286 are missing the `-y` and are failing in other quickstarts like `bastion`. I'm only noting the lines causing me issue at the moment, others might have issues.

**Comment by ThisIsQasim** [comment]
@tonynv Since the fix has been merged, can you push it to master so that this could be marked as resolved?

**Comment by ThisIsQasim** [comment]
Thank you and apologies for the constant nagging
