### ISSUE TITLE
Add support for latest cfn-tools release

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/quickstart-linux-utilities#21]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/releasehistory-aws-cfn-bootstrap.html

- https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz

**Comment by tlindsay42** [comment]
Started this in #30, but it's still buggy for Ubuntu 20.04 & 22.04 Closing in favor of #26 and duplicated in https://github.com/aws-quickstart/quickstart-linux-bastion/issues/177 to finish addressing there.
