### ISSUE TITLE
Deprecation Housekeeping

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/quickstart-linux-utilities#26]
This project is on the path to deprecation - effective 1/1/2022. We should provide a log statement that indicates as such to the downstream consumers.

@tonynv has agreed to take on adding this log statement.

**Comment by lschierer** [comment]
if it is on the path to deprecation, what replaces it?

**Comment by ivandov** [comment]
No doc in the readme, no mention of deprecation anywhere that I can find other than this issue. 

Seems relatively easy to add something to the README to tell people what to use instead? Or how to migrate away from their current usage?

For any future users that stumble upon this - I'm _guessing_ this is what they want you to use instead:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html

**Comment by tlindsay42** [comment]
Publicly archiving this project
