### ISSUE TITLE
pystache 0.6.0 drops python 2.7 support

### ISSUE THREAD

**Issue by rfox-godaddy** [aws-quickstart/quickstart-linux-utilities#28]
For the
pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
lines run via python2.7, its setup.py dependency of pystache>=0.4.0 gets satisfied by 0.6.0 which does not support python 2.7.

pystache>=0.4.0,<0.6.0 would be more appropriate.

**Comment by olivia-fl** [comment]
I've run into this issue as well, and ended up just removing quickstart-linux-utilities from our system instead of trying to fix it. It looks like it will be deprecated soon (#26), although I couldn't find reference that anywhere other than the linked issue.

**Comment by csa-bconnors** [comment]
Managed to work around this by adding `pip install "pystache>=0.4.0,<0.6.0"` earlier in my userdata. Its not pretty but it satisfies the requirements of the setup.py and will buy some time to upgrade properly.

**Comment by tlindsay42** [comment]
Closing per #26
